[package]
name = "RtlZeroPoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
winapi = { version = "0.3.9", features = ["heapapi", "libloaderapi", "winnt"] }
